export const AuthTypes = {
    REGISTER_USERS_REQUEST: "@auth/REGISTER_USERS_REQUEST",
    REGISTER_USERS_SUCCESS: "@auth/REGISTER_USERS_SUCCESS",
    REGISTER_USER_FAILURE: "@auth/REGISTER_USERS_FAILURE",
  
    LOGIN_USER_REQUEST: "@auth/LOGIN_USERS_REQUEST",
    LOGIN_USER_SUCCESS: "@auth/LOGIN_USERS_SUCCESS",
    LOGIN_USER_FAILURE: "@auth/LOGIN_USERS_FAILURE",
  
    SET_USER_LOGGED: "@auth/SET_USERS_LOGGED",
    LOGOUT_USER: "@auth/LOGOUT_USERS",
  
    CLEAR_STATE: "@auth/CLEAR_STATE"
  };